name: golangci-lint
on:
  pull_request:
    branches:
      - master
jobs:
  golangci-pr:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.38
          only-new-issues: true
          args: --timeout=5m0s
